Fix method invocation in “Beginning our Angular todo list app” (#8949)
Fixes #6763
The default to strict mode in the tsconfig for setting up an angular project as suggested in this article will give an error for this method due to the implicit any type of the parameter

```
Error: src/app/app.component.ts:28:11 - error TS7006: Parameter 'description' implicitly has an 'any' type.

28   addItem(description) {
             ~~~~~~~~~~~
```